In [1]:
coltypes= [str, int, float]

import csv
f= open('../Data/portfolio.csv')
rows= csv.reader(f)
headers= next(rows)
row= next(rows)
row

['AA', '100', '32.20']

In [2]:
r= list(zip(coltypes, row))
r

[(str, 'AA'), (int, '100'), (float, '32.20')]

In [3]:
record= [func(val) for func, val in zip(coltypes, row)]
record

['AA', 100, 32.2]

In [4]:
dict(zip(headers, record))

{'name': 'AA', 'shares': 100, 'price': 32.2}

In [5]:
#dictionary comprehension
{name: func(val) for name, func, val in zip(headers, coltypes, row)}

{'name': 'AA', 'shares': 100, 'price': 32.2}

A parsing utility function

In [6]:
import reader
portfolio= reader.read_csv_as_dicts('../Data/portfolio.csv', [str, int, float])
for s in portfolio:
    print(s)

{'name': 'AA', 'shares': 100, 'price': 32.2}
{'name': 'IBM', 'shares': 50, 'price': 91.1}
{'name': 'CAT', 'shares': 150, 'price': 83.44}
{'name': 'MSFT', 'shares': 200, 'price': 51.23}
{'name': 'GE', 'shares': 95, 'price': 40.37}
{'name': 'MSFT', 'shares': 50, 'price': 65.1}
{'name': 'IBM', 'shares': 100, 'price': 70.44}


In [7]:
rows= reader.read_csv_as_dicts('../Data/ctabus.csv', [str, str, str, int])
len(rows)

577563

In [8]:
rows[0]

{'route': '3', 'date': '01/01/2001', 'daytype': 'U', 'rides': 7354}

In [9]:
routes= {row['route'] for row in rows}
len(routes)

181

In [10]:
routeids= {id(row['route']) for row in rows}
len(routeids)

542305

Only 181 differernt routes, but 542305 different ids

In [11]:
a= 'hello world'
b= 'hello world'
a is b

False

A way to cache strings

In [12]:
import sys
a= sys.intern(a)
b= sys.intern(b)
a is b

True

In [1]:
# --- RESTART
import tracemalloc
tracemalloc.start()
from sys import intern
import reader
rows= reader.read_csv_as_dicts('../Data/ctabus.csv', [intern, str, str, int])
routeids= {id(row['route']) for row in rows}
len(routeids)

181

In [2]:
tracemalloc.get_traced_memory()

(160681074, 160691725)

Caching the date strings too

In [1]:
# --- RESTART
import tracemalloc
tracemalloc.start()
from sys import intern
import reader
rows= reader.read_csv_as_dicts('../Data/ctabus.csv', [intern, intern, str, int])
tracemalloc.get_traced_memory()

(128600713, 128630563)

In [1]:
import reader
data = reader.read_csv_as_columns('../Data/ctabus.csv', types=[str, str, str, int])
data

In [2]:
len(data)

577563

In [3]:
data[0]

{'route': '3', 'date': '01/01/2001', 'daytype': 'U', 'rides': '7354'}

In [4]:
data[1]

{'route': '4', 'date': '01/01/2001', 'daytype': 'U', 'rides': '9288'}

In [5]:
data[2]

{'route': '6', 'date': '01/01/2001', 'daytype': 'U', 'rides': '6048'}